### ISSUE TITLE
QuickCheck support missing or broken

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/codeworld#12]
The site https://code.world/haskell can deal with this program:
```haskell
import Test.QuickCheck

main = quickCheck (\n -> length [1..n] == n)
```
but here it doesn't seem to work.

**Comment by marcellussiegburg** [comment]
@nimec01 Do you know what is causing this? Could there maybe some path be missing for the reverse proxy?

**Comment by nimec01** [comment]
The cause is due to a refactoring I did when I was dealing with data privacy (not storing any student related code). The process of running code using the original CodeWorld instance is as follows:

1.  The user produces code and click on the "Run" button
2. The client makes an HTTP-Request to the server containing the source code.
3. The server will now save the original code, compile the program and save all produces files.
4. The server now responds to the original HTTP-Request with an id (`dhash`) that we can use in order to access the files create at step 2.
5. The client will now change the url of the "canvas iframe" so that the id is part of the url.
6. The iframe now issues an HTTP-Request in order to receive the produced JavaScript code.
7. ...

Step 3 is problematic as we don't want to save any user related code.  So I went ahead and change the process a bit:

Step 1-3 are the same as before, but it continues as follows:

4. The server now responds with the produced JavaScript code. https://github.com/fmidue/codeworld/blob/00d230d2dfec4729d38c281f41e27f49e94a77f1/codeworld-server/src/Main.hs#L397
5. All files that we produced in step 3 are now being deleted (regardless of the compilation outcome).
6. The client will now change the url of the "canvas iframe" so that the JavaScript code is contained in the url" (base64 encoded).
https://github.com/fmidue/codeworld/blob/00d230d2dfec4729d38c281f41e27f49e94a77f1/web/js/codeworld_shared.js#L1977
7. The iframe will now use this code in order to draw the picture / run the code.
8. ...

The problem now is that the iframe url is simply too long (`414 Request-URI Too Large`).

There is probably a better way to handle this "passing of code" but I did not come up with a better solution.

**Comment by marcellussiegburg** [comment]
Would saving the JavaScript code only on the server counter the wanted approach? If not, an alternative could be (if I did not get something wrong):

4. The server now responds to the original HTTP-Request with an id (dhash) that we can use in order to access the JavaScript code only.
5. All files that we produced in step 3 are now being deleted (regardless of the compilation outcome) except for the JavaScript code.
6. The client will now change the url of the "canvas iframe" so that the id is part of the url.
7. The iframe now issues an HTTP-Request in order to receive the produced JavaScript code.
8. ...

Or would this somehow leak user-data? In that case: could we do the following?:

4. The server now responds with an *id (hash) and* with the produced JavaScript code. 
5. All files that we produced in step 3 are now being deleted (regardless of the compilation outcome).
6. The client will now change the url of the "canvas iframe" so that the id is part of the url (and if required some data that enables communication with the client as well - e.g. websocket?).
7. The iframe now attempts to receive the produced JavaScript code from the client.
8.  ...

*Edit: added missing information*

**Comment by nimec01** [comment]
Saving the produced JavaScript code is probably not the best way to solve this. A student could for example write a program that prints their student id onto the console. This would be problematic if somehow someone unauthorized gets access to that code, wouldn't it? It would still be possible to periodically remove these files, but I don't know if that conforms with data privacy.

I also tried to implement some sort of communication between the client and iframe, but that did not work at first. However, we could try this out again.

**Comment by marcellussiegburg** [comment]
I would say: go for it!

[Maybe communicating between the iframe and main page would be enough? ([https://stackoverflow.com/questions/9153445/how-to-communicate-between-iframe-and-the-parent-site](https://stackoverflow.com/questions/9153445/how-to-communicate-between-iframe-and-the-parent-site))]

**Comment by nimec01** [comment]
> I would say: go for it!

Go for `Saving the produced JavaScript code` or `implement some sort of communication between the client and iframe`?

**Comment by marcellussiegburg** [comment]
Do you think either of it would be easier to adapt?

**Comment by nimec01** [comment]
It would probably be easier for me to implement Client <-> Iframe communication. But I will have to do some testing beforehand.

**Comment by marcellussiegburg** [comment]
Okay, then this is probably the way to go (unless you hit a dead end – in this case let us know).
