### ISSUE TITLE
Task03

### ISSUE THREAD

**Issue by mateuszcygan** [fmidue/codeworld#5]
**Shared Program**: https://code.world/haskell#PmySlg7Bf4cabEM__dlb8cQ
https://autotool.fmi.uni-due.de/haskell#P5QQi7_vjeFMVyu6nlhYbRQ

**Description**
GoogleChrome, macOS

<img width="441" alt="Screenshot 2024-04-16 at 17 57 37" src="https://github.com/fmidue/codeworld/assets/75842464/21f89a36-4121-4007-a1f3-25ea0f8c877d">
<img width="509" alt="Screenshot 2024-04-16 at 17 57 46" src="https://github.com/fmidue/codeworld/assets/75842464/d6bd1f8f-fc38-4a4c-ada6-e19e981e28ad">

**Comment by mateuszcygan** [comment]
The same error occurs in Task04 (within truncatedTime)

**Comment by marcellussiegburg** [comment]
I guess this is some reexport behaviour.
@nimec01 Can you try if the issue resolves when `String` is added to the import list here https://github.com/fmidue/codeworld/blob/51ae6ee2c07b98466a66c75fcb10f701ae32a824/codeworld-api/src/CodeWorld/FMIDUE.hs#L3

**Comment by nimec01** [comment]
The easiest fix for now would be to add `hiding (String)` after `import CodeWorld`. That is because the module `CodeWorld.FMIDUE` exports a custom `String` type (which is then imported in the `CodeWorld` module itself).

> I guess this is some reexport behaviour.

Yes. We basically reexport the `Text` type as `String`.

> Can you try if the issue resolves when String is added to the import list here

Wouldn't that lead to type mismatches? The functions require values of type `Text` but the `String` type exported in Prelude is not just `Text` right?

**Comment by jvoigtlaender** [comment]
Actually, there is probably a misunderstanding concerning the role of `CodeWorld.FMIDUE` here.

That module/renamings should only be applied for the "Math flavour of CodeWorld" (because that's what I use in the Modellierung course, and that's where I want `move` instead of `translated` etc.), but not for the "Haskell flavour of CodeWorld".

**Comment by nimec01** [comment]
> Actually, there is probably a misunderstanding concerning the role of `CodeWorld.FMIDUE` here.
> 
> That module/renamings should only be applied for the "Math flavour of CodeWorld" (because that's what I use in the Modellierung course, and that's where I want `move` instead of `translated` etc.), but not for the "Haskell flavour of CodeWorld".

So we should get rid of the default import of `CodeWorld.FMIDUE`  in the `CodeWorld` module and just include `import CodeWorld.FMIDUE` wherever it's needed, right?

**Comment by jvoigtlaender** [comment]
Probably. In any case, right now the focus is on the ProPa course and hence the "Haskell flavour". So any change that gets this conflict-free will be helpful.

If then, later, for the Modellierung course and hence the "Math flavour", an additional import can be somehow avoided/hidden, that would be nice. But not consequential at the moment.

**Comment by nimec01** [comment]
Do you even want to have these changes in the Haskell API? 

I can actually address the math and Haskell modes separately. The math mode uses a custom `base` package which includes all the CodeWorld functions (and Prelude), while the Haskell mode simply uses the `codeworld-api` package. But the custom `base` does not rely on `codeworld-api`. So I could go ahead and completely get rid of this in the Haskell version while still keeping it in the math version.

**Comment by jvoigtlaender** [comment]
> So I could go ahead and completely get rid of this in the Haskell version while still keeping it in the math version.

Sounds good.

**Comment by marcellussiegburg** [comment]
@ mateuszcygan Can you recheck if it is working now as expected?

**Comment by mateuszcygan** [comment]
Both tasks are now working as expected
